Repository Quinnsicle/arcs_tts, pull requests merged in 2025-04, with the labels that each got.

#133 Multiple fixes
  TS_Save.json
  src/AmbitionMarkers.lua
  src/Global.lua
Labels: bug

#135 Update readme, remove out of date todo doc
  README.md
  TODO.md
Labels: enhancement

#142 move song of freedom if it enters the discard
  src/CourtDiscard.lua
Labels: enhancement

#145 Increase trophy + captive zone height and add transparent walls to keep pieces within score zone
  TS_Save.json
Labels: bug, enhancement

#136 Power track update
  TS_Save.json
  src/ArcsPlayer.lua
  src/GUIDs.lua
Labels: enhancement
